import type { Document } from '../services/DocumentStore'
import { downloadStringAsFile } from '../utils/download'
import { copyToClipboard } from '../utils/clipboard'

export class ExportService {
  private static generateReportText(doc: Document): string {
    const ext = doc.extraction
    const now = new Date().toLocaleString()

    let text = `====================================\n`
    text += `NYAYA MITRA LEGAL REPORT\n`
    text += `====================================\n\n`

    text += `Document Overview\n`
    text += `------------------------------------\n`
    text += `Document Type: ${ext?.documentType || doc.classification?.type || 'Unknown'}\n`
    if (ext?.court) text += `Court: ${ext.court}\n`
    if (ext?.caseNumber) text += `Case Number: ${ext.caseNumber}\n`
    if (ext?.dates && ext.dates.length > 0) {
      text += `Date: ${ext.dates.map(d => `${d.value} (${d.type})`).join(', ')}\n`
    }
    text += `\n`

    if (doc.summary) {
      text += `Plain Language Summary\n`
      text += `------------------------------------\n`
      text += `${doc.summary}\n\n`
    }

    if (doc.timeline && doc.timeline.events.length > 0) {
      text += `Timeline\n`
      text += `------------------------------------\n`
      doc.timeline.events.forEach(event => {
        text += `• ${event.date ? `[${event.date}] ` : ''}${event.title}\n`
        text += `  ${event.description}\n\n`
      })
    }

    if (doc.rights) {
      text += `Rights & Next Steps\n`
      text += `------------------------------------\n`
      text += `Your Rights:\n${doc.rights.rightsSummary}\n\n`

      if (doc.rights.nextSteps.length > 0) {
        text += `Next Steps:\n`
        doc.rights.nextSteps.forEach((step, i) => {
          text += `${i + 1}. ${step}\n`
        })
        text += `\n`
      }

      if (doc.rights.warnings.length > 0) {
        text += `Warnings:\n`
        doc.rights.warnings.forEach(warning => {
          text += `⚠ ${warning}\n`
        })
        text += `\n`
      }
    }

    if (doc.ruleEngine && (doc.ruleEngine.sections.length > 0 || doc.ruleEngine.facts.length > 0)) {
      text += `Legal Analysis\n`
      text += `------------------------------------\n`
      if (doc.ruleEngine.sections.length > 0) {
        text += `Rules Applied: ${doc.ruleEngine.sections.join(', ')}\n\n`
      }
      if (doc.ruleEngine.facts.length > 0) {
        text += `Legal Facts:\n`
        doc.ruleEngine.facts.forEach(fact => {
          text += `- ${fact}\n`
        })
        text += `\n`
      }
    }

    text += `====================================\n`
    text += `Generated by Nyaya Mitra\n`
    text += `Generation Time: ${now}\n`
    text += `====================================\n`

    return text
  }

  static downloadJSON(doc: Document) {
    const exportData = {
      metadata: {
        generatedAt: new Date().toISOString(),
        processingTime: doc.ocr?.processingTime || 0,
        version: "1.0",
        documentId: doc.id
      },
      classification: doc.classification,
      extraction: doc.extraction,
      ruleEngine: doc.ruleEngine,
      timeline: doc.timeline,
      summary: doc.summary,
      rights: doc.rights
    }

    const jsonString = JSON.stringify(exportData, null, 2)
    downloadStringAsFile(jsonString, `nyaya-mitra-report-${doc.id}.json`, 'application/json')
  }

  static downloadSummary(doc: Document) {
    const text = this.generateReportText(doc)
    downloadStringAsFile(text, `legal-summary-${doc.id}.txt`, 'text/plain;charset=utf-8')
  }

  static async copySummary(doc: Document): Promise<boolean> {
    const text = this.generateReportText(doc)
    return await copyToClipboard(text)
  }

  static printReport() {
    window.print()
  }
}
